name: Build and Publish binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build binaries using pico-sdk 
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/dev lukstep/raspberry-pi-pico-sdk:latest /bin/sh -c "cd /home/dev && mkdir build && cd build && cmake .. && make -j4"

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/test/integrationTest/integrationTest.uf2
            build/test/integrationTest/integrationTest.elf
            build/test/integrationTest/integrationTest.bin
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
      
      - name: Install zip and jq
        run: sudo apt-get install zip jq

      - name: Rename and Package binaries
        id: package
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          mv integrationTest.elf pico-rgb2hdmi-$TAG_NAME.elf
          mv integrationTest.bin pico-rgb2hdmi-$TAG_NAME.bin
          mv integrationTest.uf2 pico-rgb2hdmi-$TAG_NAME.uf2
          shopt -s nullglob
          zip pico-rgb2hdmi-$TAG_NAME.zip pico-rgb2hdmi*
          echo "::set-output name=zip_file::pico-rgb2hdmi-$TAG_NAME.zip"

      - name: Get Release ID
        id: get_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_ID=$(curl --silent --show-error --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME" | jq .id)
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets
          asset_path: ./${{ env.zip_file }}
          asset_name: ${{ env.zip_file }}
          asset_content_type: application/zip
